### ISSUE TITLE
K-mean runs

### ISSUE THREAD

**Issue by twesterhout** [mlp2018/BagofWords#16]
In the tutorial, the number of clusters is taken to be a fraction of the number of reviews. Suppose now, we have a `KMeans` object with some certain number of clusters. We run `fit_predict` on the training data set. This runs the actual k-means algorithm and, after converging, returns the labeling of words (i.e. which word corresponds to which cluster). Then we train our classifier etc. Now, to use the classifier to make predictions, our test data should have the same format as the training data. This means that the number of clusters should be the same. There are two ways to achieve this:
1) Run k-means on the test data set with the same number of clusters as we had for the training data set.
2) Skip the k-means (i.e. use the centroids we obtained while training) and only run the labeling part on the test data.

I think option 2 is the correct one, but I'm not entirely sure. Comments?

**Comment by twesterhout** [comment]
Actually, there's a third option, the one taken in the tutorial. After running k-means and prediction on the training data set, we create a `word→cluster` map. We then use this map rather than the labeling algorithm to map words to clusters. The con here is that if we encounter a word in the test data that we haven't seen before (while training), it gets mapped to nothing and is thus not taken into consideration when creating bags of centroids.

**Comment by ghost** [comment]
I don't understand how option 2 would work. As you say, the test data should have the same format as the training data. How would this be achieved in option 2?

Options 1 and 3 both make sense. It seems that 1 would be more accurate whereas 3 would be faster. This could be an issue for later exploration:
- How much faster is 3 as compared to 1?
- How much more accurate is 1 as compared to 3? 
And then decide between these two options based on the results.

**Comment by twesterhout** [comment]
I could've done a better job explaining, sorry. Let me elaborate. Say, we run k-means clustering on some training data with `N` clusters. We now have a list of coordinates (in word2vec feature space) of `N` centroids, and "bag of centroids" representation can be used to convert a review (i.e. a list of words) into a single `N`-dimensional vector. This part is the same in all three variants. We now try to process the test data.

1) We just repeat the above procedure for the test data. Pro is that this is extremely simple both conceptually and from the programming point of view. Could be slow, but never mind that for now. The biggest con with this approach is that the positions of centroids are forgotten, i.e. we have learned absolutely nothing from the training data :) (correct me if I'm wrong here) Hence, we probably don't want to use this approach, i.e. we want to use the obtained centroids somehow.
2) The first way to do that is to just run the "labeling" on the data set. What this means is that for each point, we assign it to the closest (plain Euclidean metric is used, I think) cluster. Having obtained a mapping from words from the test data set to clusters, we can again use "bag of centroids".
3) Alternatively, skip the labeling part. We encountered quite many words during training, for them we immediately know which cluster they correspond to. There could, however, be words we haven't seen yet. In this case, there's no simple way to assign them to clusters. A warning is then issued and the word in question doesn't contribute to the "bag".

Does this make sense?

**Comment by ghost** [comment]
This is much clearer, thanks! I now understand that 1 is not a good option.

If I understand it correctly, 2 is slower than 3 but has the advantage of using all of the words in the test data, whereas 3 is faster than 2 but ignores those words in the test data that were not seen in the training data.

Correct?

**Comment by twesterhout** [comment]
Yes, that sounds about right.

**Comment by ghost** [comment]
Okay :) Well, I guess we could make an issue out of it: investigating how many percent of words are ignored in option 3, and how much faster it is as compared to option 2. Depending on those outcomes we can choose which option to implement. What do you think?

**Comment by twesterhout** [comment]
I actually think that the cost of both operations is negligible :) I mean, "labeling" is just one half of a step in k-means. Currently, the upper bound on number of steps is 300, and there are 10 runs... So I would expect the labeling to take less than 1% of time. (I'll time it if I find the time)

**Comment by ghost** [comment]
That sounds reasonable, so we could also just go for option 2 directly?

**Comment by twesterhout** [comment]
OK, I'll add it as another "task".

**Comment by ghost** [comment]
Perfect!
