### ISSUE TITLE
record of accuracies we find for different models?

### ISSUE THREAD

**Issue by aranas** [mlp2018/BagofWords#29]
Now that the cross-validation and split is in place we can play with different algorithms/data preprocessing/word2vec models and compare their scores on our 10% test data. It would probably be good if we would keep track of the models we have trained and their outcome on the testdata. Something like saving the conf file plus the score and the date and who ran it. 

Do you think this is a good idea and have any suggestions on how to structure it?

**Comment by twesterhout** [comment]
I like this idea. Not sure about how to bring it to life though...

**Comment by ghost** [comment]
Definitely a very good idea. An easy solution could be to record all our model runs in a shared Google Sheets document, but that would be manual labor whereas saving the conf file could be done automatically. However, a sheet is easier to oversee (e.g., what models have we already run, and what models still need to be run), as compared to a directory with config files.
