### ISSUE TITLE
Save instance of NeuralNetworkClassifier to file

### ISSUE THREAD

**Issue by ghost** [mlp2018/BagofWords#33]
This should do it, but it doesn't:

```
with open('trained_nn_classifier.pickle', 'wb') as pickle_out:
    pickle.dump(b, pickle_out)

Traceback (most recent call last):

  File "<ipython-input-191-44eb863ebdf0>", line 2, in <module>
    pickle.dump(b, pickle_out)

AttributeError: Can't pickle local object 'DNNClassifier.__init__.<locals>._model_fn'
```

Somehow it still goes wrong with regard to our NeuralNetworkClassifier instance containing an instance of the DNNClassifier class.

In the [documentation](https://docs.python.org/3.1/library/pickle.html#pickling-class-instances) I also found this:

```
def save(obj):
    return (obj.__class__, obj.__dict__)
```

Which leads to:

```
save(b)
Out[195]: 
(__main__.NeuralNetworkClassifier,
 {'batch_size': 100,
  'classifier': <tensorflow.python.estimator.canned.dnn.DNNClassifier at 0x1a13006db38>,
  'n_classes': 2,
  'n_hidden_units1': 10,
  'n_hidden_units2': 10,
  'n_steps': 1000})
```

A workaround could be to write the above tuple to a file, but that wouldn't be great because it wouldn't store the actual model, but only the pointer to where it is temporarily stored in memory on a specific computer.

**Comment by Cantoria** [comment]
How can i read model from pickled pointer?

**Comment by twesterhout** [comment]
Currently, you can't. PRs are welcome though.
