### ISSUE TITLE
Replicate tutorial but using pre-trained word2vec

### ISSUE THREAD

**Issue by ghost** [mlp2018/BagofWords#5]

**Comment by aranas** [comment]
Option 1: Facebooks pretrained "fastText"
https://github.com/facebookresearch/fastText/blob/master/pretrained-vectors.md

**Comment by twesterhout** [comment]
[Here's](http://mccormickml.com/2016/04/12/googles-pretrained-word2vec-model-in-python/) a blog post on how to use Google's pre-trained model from within Python. And [here's](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit) the download link itself.
